<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>iPresenterPlux.Edge.Windows</RootNamespace>
    <AssemblyName>iPresenterPlux.Edge.Windows</AssemblyName>
    <UseWindowsForms>false</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../iPresenterPlux.Edge.Core/iPresenterPlux.Edge.Core.csproj" />
  </ItemGroup>
</Project>
